name: Testing Configuration Variables

on: workflow_dispatch

env:
  cloud: aws cloud

job:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello to Mona"
        run: echp "$Greeting $first_name is using $cloud with project ${{vars.PROJECT_ID}}"
        env:
          first_name: Lehlohonolo
