name: Testing Secret Variables


on:
  workflow_dispatch

env:
  ACTION_STEP_DEBUG: true

jobs:
  test_secret_variables:
    runs-on: ubuntu-latest  
    steps:
      - name: "Checking Secret Variable"
        run: | 
          echo "secret_value : ${{secrets.MY_KEY}}"
