name: Testing Workflow Variables

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs_on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona, it's Monday"
      run: echo "$Greeting $first_name is using $cloud!"
      env:
        first_name: lehlohonolo
